const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const vm=require('vm');const ts=require('typescript');const path=require('path');
function load(file,mocks={},env={}){const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../src/lib',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,process:{env},URL,Date,Intl,console,require:n=>n==='server-only'?{}:mocks[n]});return module.exports;}
const template=load('order-email-template.ts');
const order={id:'11111111-1111-4111-8111-111111111111',view_token:'a'.repeat(64),payment_mode:'live',status:'paid',fulfillment_status:'shipped',tracking_reference:'https://track.example.com/abc',customer:{name:'<img src=x>',email:'test@example.com',street:'A & B 1',postal_code:'4561AA',city:'Hulst',country:'NL'},items:[{id:'x',name:'<b>Polish</b>',quantity:2,unit_price_cents:3495}],shipping_cents:0,total_cents:6990};
test('customer content is escaped and snapshot prices are used',()=>{const m=template.orderEmail(order,'confirmation','https://www.debumperbank.nl','Retourinformatie <test>');assert.match(m.html,/&lt;img src=x&gt;/);assert.match(m.html,/&lt;b&gt;Polish&lt;\/b&gt;/);assert.match(m.text,/69,90/);assert.match(m.text,/Retourinformatie <test>/);assert.ok(!m.html.includes('<img src=x>'));assert.ok(!m.text.includes('Moneybird'));});
test('tracking URLs allow HTTPS only and no credentials',()=>{for(const v of ['javascript:alert(1)','http://x.test','https://user:password@x.test','TRACK123'])assert.equal(template.safeTrackingUrl(v),null);assert.equal(template.safeTrackingUrl('https://x.test/a'),'https://x.test/a');});
test('shipping mail handles plain tracking code without unsafe link',()=>{const m=template.orderEmail({...order,tracking_reference:'javascript:alert(1)'},'shipped','https://www.debumperbank.nl','');assert.ok(!m.html.includes('href="javascript:'));assert.ok(!m.html.includes('Volg je pakket'));});
function fixture({enabled=true,mode='live',status='paid',fulfillment='shipped',config=true,failSend=false,failSave=false}={}){
 let row=null,calls=0;
 const db={from:table=>{let op='read',values,filter;return {select(){return this},eq(k,v){if(k==='state')filter=v;return this},upsert(v){if(!row)row={...v,state:'pending'};return Promise.resolve({error:null})},update(v){op='update';values=v;return this},single(){return this.run()},maybeSingle(){return this.run()},then(resolve,reject){return this.run().then(resolve,reject)},async run(){if(table==='shop_orders')return {data:{...order,payment_mode:mode,status,fulfillment_status:fulfillment}};if(op==='update'){if(failSave&&values.state==='sent')return {error:{code:'failed'}};if(filter&&row.state!==filter)return {data:null};Object.assign(row,values);return {data:{...row}};}return {data:row};}}}};
 const env={CUSTOMER_EMAILS_ENABLED:String(enabled),...(config?{NOTIFY_FROM_EMAIL:'De Bumperbank <info@debumperbank.nl>',SHOP_CUSTOMER_INFORMATION:'Aankoopinformatie'}:{})};
 const api=load('order-emails.ts',{'@/lib/supabase/admin':{createAdminClient:()=>db},'@/lib/resend':{getResendClient:()=>({emails:{send:async()=>{calls++;if(failSend)throw new Error('Timeout');return {data:{id:'mail_1'}}}}})},'@/lib/mollie':{shopOrigin:()=> 'https://www.debumperbank.nl'},'./order-email-template':template},env);
 return {send:k=>api.sendOrderEmail(order.id,k||'confirmation'),calls:()=>calls,row:()=>row};
}
test('repeated and concurrent sends use one durable claim',async()=>{const f=fixture();await Promise.allSettled([f.send(),f.send()]);await f.send();assert.equal(f.calls(),1);assert.equal(f.row().state,'sent');});
test('test, unpaid and disabled orders do not send',async()=>{for(const options of [{mode:'test'},{status:'pending'},{enabled:false}]){const f=fixture(options);await f.send();assert.equal(f.calls(),0);}});
test('shipping requires shipped order',async()=>{const f=fixture({fulfillment:'unfulfilled'});await f.send('shipped');assert.equal(f.calls(),0);});
test('missing production configuration blocks before claim',async()=>{const f=fixture({config:false});await assert.rejects(f.send(),/configuration/);assert.equal(f.calls(),0);assert.equal(f.row(),null);});
test('ambiguous provider outcome never blindly resent',async()=>{const f=fixture({failSend:true});await assert.rejects(f.send(),/review/);await assert.rejects(f.send(),/review/);assert.equal(f.calls(),1);assert.equal(f.row().state,'review_required');});
test('failure saving provider success cannot duplicate mail',async()=>{const f=fixture({failSave:true});await assert.rejects(f.send(),/uncertain/);await assert.rejects(f.send(),/review/);assert.equal(f.calls(),1);});
