const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');const vm=require('node:vm');
function load(relative,mocks={}){const file=path.resolve(__dirname,'../src',relative);const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,require:name=>Object.hasOwn(mocks,name)?mocks[name]:name==='server-only'?{}:load(name.startsWith('@/')?name.slice(2)+'.ts':path.relative(path.resolve(__dirname,'../src'),path.resolve(path.dirname(file),name+'.ts')),mocks),process:{env:{MOLLIE_API_KEY:'test_example',NEXT_PUBLIC_SITE_URL:'https://example.com'}},URL,AbortSignal,console});return module.exports;}
const shop=load('lib/shop.ts'),cart=load('lib/cart.ts');const id='11111111-1111-4111-8111-111111111111';const key='22222222-2222-4222-8222-222222222222';
function input(){return {checkout_key:key,consent:true,expected_total_cents:4494,items:[{id,quantity:1}],customer:{name:'Test',email:'TEST@example.com',phone:'',street:'Teststraat 1',postal_code:'4561AA',city:'Hulst',country:'NL'}};}
for(const [country,amount,fee] of [['NL',4999,499],['BE',4999,699],['NL',5000,0],['BE',5000,0]])test(`shipping ${country} ${amount}`,()=>assert.equal(shop.shippingCost(amount,country),fee));
test('unsupported destination rejected',()=>assert.throws(()=>shop.shippingCost(100,'DE')));
test('quote uses catalogue price, not injected client price',()=>{const q=shop.quoteOrder([{id,quantity:2,price_cents:1}],[{id,name:'Coating',price_cents:3995}],'BE');assert.equal(q.total_cents,7990);assert.equal(q.shipping_cents,0)});
for(const products of [[],[{id,name:'Coating',price_cents:-1}],[{id,name:'Coating',price_cents:3995,is_available:false}]])test('reject unavailable or invalid product '+JSON.stringify(products),()=>assert.throws(()=>shop.quoteOrder([{id,quantity:1}],products,'NL')));
test('checkout normalizes email',()=>assert.equal(shop.validateCheckout(input()).customer.email,'test@example.com'));
for(const quantity of [0,-1,1.5,21,'1'])test('reject quantity '+quantity,()=>{const b=input();b.items[0].quantity=quantity;assert.throws(()=>shop.validateCheckout(b))});
test('duplicate items rejected',()=>{const b=input();b.items.push({id,quantity:1});assert.throws(()=>shop.validateCheckout(b))});
test('consent required',()=>{const b=input();b.consent=false;assert.throws(()=>shop.validateCheckout(b))});
test('country postcode validation',()=>{const b=input();b.customer.country='BE';assert.throws(()=>shop.validateCheckout(b));b.customer.postal_code='1000';assert.equal(shop.validateCheckout(b).customer.country,'BE')});
test('cart merges and bounds quantities, drops invalid data',()=>{const rows=cart.normalizeCart([{id,quantity:15},{id,quantity:15},{id:'bad',quantity:2}]);assert.equal(rows.length,1);assert.equal(rows[0].quantity,20)});
const order={id:key,total_cents:4494,payment_id:'tr_test123',payment_mode:'test'};const payment={id:'tr_test123',mode:'test',status:'paid',metadata:{order_id:key},amount:{currency:'EUR',value:'44.94'}};
const matches=load('lib/shop-payments.ts',{'@/lib/supabase/admin':{},'@/lib/mollie':{},'@/lib/resend':{}}).paymentMatches;
test('matching payment accepted',()=>assert.equal(matches(payment,order),true));
for(const override of [{amount:{currency:'EUR',value:'0.01'}},{amount:{currency:'USD',value:'44.94'}},{mode:'live'},{id:'tr_wrong'},{metadata:{order_id:id}}])test('mismatched payment rejected '+JSON.stringify(override),()=>assert.equal(matches({...payment,...override},order),false));
async function syncFixture(status,alreadyPaid=false){let updates=0,notifications=0;const row={...order,status:alreadyPaid?'paid':'open',customer:{name:'Test',email:'x@example.com',phone:'',street:'Straat 1',postal_code:'1000',city:'Brussel',country:'BE'},items:[{id,name:'Test',quantity:1,unit_price_cents:3995}],shipping_cents:499,notified_at:alreadyPaid?'2026-01-01':null};let pending;
 const db={from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:row,error:null})})}),update:v=>{pending=v;return {eq:()=>({neq:async(_,exclude)=>{if(row.status!==exclude){updates++;Object.assign(row,pending)}return {error:null}},then:resolve=>resolve({error:null})})}}})};
 const module=load('lib/shop-payments.ts',{'@/lib/supabase/admin':{createAdminClient:()=>db},'@/lib/mollie':{mollieRequest:async()=>({...payment,status}),mollieMode:()=> 'test',shopOrigin:()=> 'https://example.com'},'@/lib/resend':{notifyAdmin:async()=>{notifications++;return true}}});await module.synchronizePayment('tr_test123');return {updates,notifications,row};}
test('verified paid callback updates order and notifies admin',async()=>{const r=await syncFixture('paid');assert.equal(r.row.status,'paid');assert.equal(r.notifications,1)});
test('late open callback cannot downgrade paid order',async()=>{const r=await syncFixture('open',true);assert.equal(r.row.status,'paid');assert.equal(r.updates,0);assert.equal(r.notifications,0)});
test('duplicate paid callback does not notify twice',async()=>{const r=await syncFixture('paid',true);assert.equal(r.notifications,0);assert.equal(r.updates,0)});
